[versions]
spock = "2.3-groovy-3.0"

[libraries]
mavenPlugin-annotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations" }
mavenPluginTools-bom = { module = "org.apache.maven.plugin-tools:maven-plugin-tools", version = "3.15.1" }
mavenPluginTools-api = { module = "org.apache.maven.plugin-tools:maven-plugin-tools-api" }
mavenPluginTools-annotations = { module = "org.apache.maven.plugin-tools:maven-plugin-tools-annotations" }
mavenPluginTools-java = { module = "org.apache.maven.plugin-tools:maven-plugin-tools-java" }
mavenPluginTools-generators = { module = "org.apache.maven.plugin-tools:maven-plugin-tools-generators" }
mavenPlugin-api = { module = "org.apache.maven:maven-plugin-api", version = "3.9.9" }
sisu-injectPlexus = { module = "org.sonatype.sisu:sisu-inject-plexus", version = "2.6.0" }
plexus-velocity = { module = "org.codehaus.plexus:plexus-velocity", version = "2.2.0" }
qdox = { module = "com.thoughtworks.qdox:qdox", version = { require = "2.0-M9", prefer = "2.0.0" } }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-junit4 = { module = "org.spockframework:spock-junit4", version.ref = "spock" }
junit4 = { module = "junit:junit", version = "4.13.2" }
junitVintageEngine = { module = "org.junit.vintage:junit-vintage-engine", version = "5.12.0" }
takariPluginTesting = { module = "io.takari.maven.plugins:takari-plugin-integration-testing", version = "3.0.5" }
commonsLang = { module = "org.apache.commons:commons-lang3", version = "3.17.0" }
exemplar-sampleCheck = { module = "org.gradle.exemplar:samples-check", version = "1.0.2" }
